### ISSUE TITLE
Don't use a npc in quests

### ISSUE THREAD

**Issue by AbelMG** [SkytAsul/BeautyQuests#10]
**Is your feature request related to a problem? Please describe.**
I don't wanna use npc's to start of finish the quests, for that reason the command /quests start (player) (quest), that should give the quest to the player, could you do this in the gui? quests without npc's
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by AbelMG** [comment]
what do you mean, haha

**Comment by AbelMG** [comment]
Oh, but I mean to create quests and finish them, a option in the config to finish quests automatically or give this to the npc, you know? I can't create a quest if I don't choose a npc

**Comment by SkytAsul** [comment]
At worst, give an NPC but completely hide him somewhere, then players will not be able to start the quest without the command !

De : AbelMG
Envoyé le :mercredi 5 septembre 2018 23:08
À : SkytAsul/BeautyQuests
Cc : SkytAsul; Comment
Objet :Re: [SkytAsul/BeautyQuests] Don't use a npc in quests (#10)

Oh, but I mean to create quests and finish them, a option in the config to finish quests automatically or give this to the npc, you know? I can't create a quest if I don't choose a npc
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by madtomic** [comment]
use NPC 0 to keep all your quests for creating quests and you can still use command to start/quit quests.

**Comment by SkytAsul** [comment]
Done in https://github.com/SkytAsul/BeautyQuests/commit/119addfba0c9b1e1999f6ab4fc6bc981574a0b8a
