### ISSUE TITLE
Don't working the name of mobs.

### ISSUE THREAD

**Issue by DrLuzbel** [SkytAsul/BeautyQuests#269]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.

When i define a mission to kill a mob i use the option "Name of mob" with Shift + left click, however when i kill other mob to same type, the quest is completed. I try to rename a mob with "tags" an "anvil" and with the comand /tag, but dont work.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
Are there error messages in the console or in the chat?

No have errors, only the quest is completed.

**Software**
BeautyQuests version: 0.20.1
Game version: 1.19
Server version: 1.19
Server type (e.i. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)?
Yes, ViaVersion 4.6.0

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
The "name of mob" option is simply to customize the name in the quest description, scoreboard and gui. It is not meant to "filter" the mobs you are killing.
If you want a stage where you have to kill a mob with a certain name, you'll have to use BeautyQuestsAddon because I have not added such a feature in vanilla BeautyQuests.
