### ISSUE TITLE
Middle-click does not work

### ISSUE THREAD

**Issue by Arko1994** [SkytAsul/BeautyQuests#273]
The middle mouse button to remove does not work. 
It works like the normal left\right button and opens the edit menu instead of removing.
No error messages.
![image](https://user-images.githubusercontent.com/26926755/235389351-d8c4c69c-8818-4f48-bde4-50a63a22f964.png)
![image](https://user-images.githubusercontent.com/26926755/235390558-0a8e7b20-529e-4ab5-9cae-bd8254f174d4.png)

**Software**
BeautyQuests version: 0.20.1
Game version: 1.19.4
Server version: 1.19.4
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? no

**Comment by mvez73** [comment]
You need to be in creative for the middle click to work

**Comment by StevenGoh-YH** [comment]
> You need to be in creative for the middle click to work

Hi, I am in creative mode and I can verify that the middle-click does not work.

It might be a better option to indicate the actual action key instead of using middle-click, if it is actually bind to a default minecraft action. Middle-click could be easily changed for most players.

However, I've tested all the buttons usable, non worked too.

Hopefully this can be resolved. Thanks.

**Comment by SkytAsul** [comment]
The middle-click will be changed to shift+left click in the next update.

**Comment by SkytAsul** [comment]
It has been in 1.0 dev builds
