### ISSUE TITLE
locales translations disappears

### ISSUE THREAD

**Issue by Kasviss** [SkytAsul/BeautyQuests#281]
**Describe the bug**	
us translations to finnish was disappears just? idk why?

**Reproduction**
we translated file to finnish but it's now english

**Screenshots, error messages**
below is a picture of the file
![image](https://github.com/SkytAsul/BeautyQuests/assets/139772321/15adf102-d271-45d3-9575-3fe48a212320)

**Software**
BeautyQuests version: 0.20.1
Game version: 1.20.1
Server version: 1.20.1
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)? yes

**Comment by SkytAsul** [comment]
Must be because your translated file had a syntax error. I don't know why but sometimes the spigot yaml engine resets files when they are not correct.
You should do backup of your files when you edit them. Also check logs of the server the first time you launched it with your translated file.
Anyway, the preferred way of translation is on [Crowdin](https://crowdin.com/project/beautyquests), because other players will benefit of it as well.

**Comment by Kasviss** [comment]
why when I translated the files to Finnish, it looks like this
![image](https://github.com/SkytAsul/BeautyQuests/assets/139772321/6600643e-eea8-46c5-a443-45863eb59e35)

**Comment by SkytAsul** [comment]
Oh damn I didn't know you would do it this fast. That's because I updated a few days ago the translations for the 1.0 update, hence the new variable names instead of old {0}, {1}... Just wait for the update, it will come soon! And if you are up to try the beta of the update, tell me!

**Comment by Kasviss** [comment]
Yeah I did 34% of the translations yesterday and today 😄

**Comment by Kasviss** [comment]
and so, I had to ask, is it possible to change the prefix somehow?

**Comment by SkytAsul** [comment]
Yeah there is a line in the translation file with the prefix :)

**Comment by Kasviss** [comment]
can I so try your 1.0 update right now?

**Comment by SkytAsul** [comment]
https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/
You should read the informations in the [#beautyquests-announcement channel on my discord server](https://discord.gg/UXrqmMWgUq) before upgrading!
